ONLY = [
    "application_status",
    "application_date",
    "reapplication_date",
    "payment_status",
    "send_payment_date",
    "resend_payment_date",
    "id",
    "first_name",
    "last_name",
    "profession",
    "sex",
    "summary",
    "country",
    "email",
    "phone",
    "address",
    "birthday",
    "website",
    "comment_from_administrator",
]

ADMIN_ONLY = [
    "application_status",
    "payment_status",
    "id",
    "first_name",
    "last_name",
    "phone",
    "email",
]
