"""added comment_from_administrator

Revision ID: 10b9368dab94
Revises: affb034ec7ad
Create Date: 2019-01-18 18:54:09.360816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b9368dab94'
down_revision = 'affb034ec7ad'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment_from_administrator', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comment_from_administrator')
    # ### end Alembic commands ###
