"""renamed column

Revision ID: 21885d36d179
Revises: 5b93d9ca7357
Create Date: 2019-03-06 14:54:35.373819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21885d36d179'
down_revision = '5b93d9ca7357'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('officialcommunications', 'title', new_column_name="name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('officialcommunications', 'name', new_column_name="title")

    # ### end Alembic commands ###
