"""added skill fields

Revision ID: 30dda17cf381
Revises: d116d89dc88b
Create Date: 2019-03-04 15:30:37.275084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dda17cf381'
down_revision = 'd116d89dc88b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('education_type', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('from_year', sa.Date(), nullable=True))
    op.add_column('skills', sa.Column('releaser', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('to_year', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(), nullable=True))
    op.drop_column('users', 'industry')
    op.drop_column('users', 'headline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'sex')
    op.drop_column('skills', 'to_year')
    op.drop_column('skills', 'releaser')
    op.drop_column('skills', 'from_year')
    op.drop_column('educations', 'education_type')
    # ### end Alembic commands ###
