"""third

Revision ID: 316b94c7c69c
Revises: 98d1aa97a453
Create Date: 2019-07-15 17:12:24.885699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316b94c7c69c'
down_revision = '98d1aa97a453'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
