"""fourth

Revision ID: 333e539fa199
Revises: b0f7330b28b4
Create Date: 2019-03-03 03:16:58.097353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333e539fa199'
down_revision = 'b0f7330b28b4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('educations', 'grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
