"""added 6 new classes, official communication etc

Revision ID: 42c2a22eb076
Revises: bf8a21f5f8a6
Create Date: 2019-03-06 02:43:00.437632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c2a22eb076'
down_revision = 'bf8a21f5f8a6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizationgroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediaorganizationgroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('organizationgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizationgroup_id'], ['organizationgroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officialcommunications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediaofficialcommunications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('officialcommunication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['officialcommunication_id'], ['officialcommunications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officialcomments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('officialcommunication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['officialcommunication_id'], ['officialcommunications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizationgroup_officialcommunication',
    sa.Column('organizationgroup_id', sa.Integer(), nullable=True),
    sa.Column('officialcommunication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['officialcommunication_id'], ['officialcommunications.id'], ),
    sa.ForeignKeyConstraint(['organizationgroup_id'], ['organizationgroups.id'], )
    )
    op.create_table('mediaofficialcomments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('officialcomment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['officialcomment_id'], ['officialcomments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tests')
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'user_id')
    op.add_column('users', sa.Column('organizationgroup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizationgroups', ['organizationgroup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organizationgroup_id')
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'author_id')
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'author_id')
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tests_pkey'),
    sa.UniqueConstraint('email', name='tests_email_key')
    )
    op.drop_table('mediaofficialcomments')
    op.drop_table('organizationgroup_officialcommunication')
    op.drop_table('officialcomments')
    op.drop_table('mediaofficialcommunications')
    op.drop_table('officialcommunications')
    op.drop_table('mediaorganizationgroups')
    op.drop_table('organizationgroups')
    # ### end Alembic commands ###
