"""added application_date

Revision ID: 5b93d9ca7357
Revises: 42c2a22eb076
Create Date: 2019-03-06 13:57:15.710222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b93d9ca7357'
down_revision = '42c2a22eb076'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('application_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('profession', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profession')
    op.drop_column('users', 'application_date')
    # ### end Alembic commands ###
