"""added rejected date

Revision ID: 9607271b5e5b
Revises: b362d8171cec
Create Date: 2019-03-13 20:38:30.757183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9607271b5e5b'
down_revision = 'b362d8171cec'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rejected_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rejected_date')
    # ### end Alembic commands ###
