"""added timestamps everywhere

Revision ID: 96a19bea64e1
Revises: 9607271b5e5b
Create Date: 2019-03-13 22:38:12.747576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96a19bea64e1'
down_revision = '9607271b5e5b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'time', new_column_name="timestamp")
    op.add_column('educations', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('experiences', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('mediaeducations', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('mediaexperiences', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('mediaofficialcomments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('mediaofficialcommunications', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('mediaorganizationgroups', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('mediaskills', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('mediausers', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('messagegroups', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('messagerecipients', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'time', new_column_name="timestamp")
    op.add_column('notifications', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('officialcomments', 'time', new_column_name="timestamp")
    op.alter_column('officialcommunications', 'time', new_column_name="timestamp")
    op.add_column('organizationgroups', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('posts', 'time', new_column_name="timestamp")
    op.add_column('skills', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'timestamp')
    op.alter_column('posts', 'timestamp', new_column_name="time")
    op.drop_column('organizationgroups', 'timestamp')
    op.alter_column('officialcommunications', 'timestamp', new_column_name="time")
    op.alter_column('officialcomments', 'timestamp', new_column_name="time")
    op.drop_column('notifications', 'timestamp')
    op.alter_column('messages', 'timestamp', new_column_name="time")
    op.drop_column('messagerecipients', 'timestamp')
    op.drop_column('messagegroups', 'timestamp')
    op.drop_column('mediausers', 'timestamp')
    op.drop_column('mediaskills', 'timestamp')
    op.drop_column('mediaorganizationgroups', 'timestamp')
    op.drop_column('mediaofficialcommunications', 'timestamp')
    op.drop_column('mediaofficialcomments', 'timestamp')
    op.drop_column('mediaexperiences', 'timestamp')
    op.drop_column('mediaeducations', 'timestamp')
    op.drop_column('groups', 'timestamp')
    op.drop_column('experiences', 'timestamp')
    op.drop_column('events', 'timestamp')
    op.drop_column('educations', 'timestamp')
    op.alter_column('comments', 'timestamp', new_column_name="time")

    # ### end Alembic commands ###
