"""added accepted_date

Revision ID: ab09683b993d
Revises: 21885d36d179
Create Date: 2019-03-10 15:38:19.468716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab09683b993d'
down_revision = '21885d36d179'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_date')
    # ### end Alembic commands ###
