"""added media_filename and media_url

Revision ID: affb034ec7ad
Revises: 105407457aed
Create Date: 2019-01-18 06:31:47.121016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affb034ec7ad'
down_revision = '105407457aed'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('media_filename', sa.String(), nullable=True))
    op.add_column('medias', sa.Column('media_url', sa.String(), nullable=True))
    op.drop_column('medias', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('medias', 'media_url')
    op.drop_column('medias', 'media_filename')
    # ### end Alembic commands ###
