"""removed company

Revision ID: b362d8171cec
Revises: f70e42dd1ec9
Create Date: 2019-03-13 20:26:52.002346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b362d8171cec'
down_revision = 'f70e42dd1ec9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
