"""added title to experience

Revision ID: b6c555e5eaf3
Revises: ab09683b993d
Create Date: 2019-03-11 23:17:40.775139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c555e5eaf3'
down_revision = 'ab09683b993d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'title')
    # ### end Alembic commands ###
