"""second

Revision ID: bf8a21f5f8a6
Revises: 8dd936dffff5
Create Date: 2019-03-05 22:23:26.530553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8a21f5f8a6'
down_revision = '8dd936dffff5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiences', 'title', new_column_name="employer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiences', 'employer', new_column_name="title")
    # ### end Alembic commands ###
