"""renamed from_date from from_year

Revision ID: db88ee2ef4c6
Revises: 30dda17cf381
Create Date: 2019-03-04 16:18:43.378285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db88ee2ef4c6'
down_revision = '30dda17cf381'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educations', 'from_year', new_column_name="from_date")
    op.alter_column('educations', 'to_year', new_column_name="to_date")
    op.alter_column('skills', 'from_year', new_column_name="from_date")
    op.alter_column('skills', 'to_year', new_column_name="to_date")
    # op.add_column('educations', sa.Column('from_date', sa.Date(), nullable=True))
    # op.add_column('educations', sa.Column('to_date', sa.Date(), nullable=True))
    # op.drop_column('educations', 'to_year')
    # op.drop_column('educations', 'from_year')
    # op.add_column('skills', sa.Column('from_date', sa.Date(), nullable=True))
    # op.add_column('skills', sa.Column('to_date', sa.Date(), nullable=True))
    # op.drop_column('skills', 'to_year')
    # op.drop_column('skills', 'from_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educations', 'from_date', new_column_name="from_year")
    op.alter_column('educations', 'to_date', new_column_name="to_year")
    op.alter_column('skills', 'from_date', new_column_name="from_year")
    op.alter_column('skills', 'to_date', new_column_name="to_year")
    # op.add_column('skills', sa.Column('from_year', sa.DATE(), autoincrement=False, nullable=True))
    # op.add_column('skills', sa.Column('to_year', sa.DATE(), autoincrement=False, nullable=True))
    # op.drop_column('skills', 'to_date')
    # op.drop_column('skills', 'from_date')
    # op.add_column('educations', sa.Column('from_year', sa.DATE(), autoincrement=False, nullable=True))
    # op.add_column('educations', sa.Column('to_year', sa.DATE(), autoincrement=False, nullable=True))
    # op.drop_column('educations', 'to_date')
    # op.drop_column('educations', 'from_date')
    # ### end Alembic commands ###
