"""renamed register_status

Revision ID: ee54eb1f505d
Revises: 96a19bea64e1
Create Date: 2019-03-19 18:10:44.670999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee54eb1f505d'
down_revision = '96a19bea64e1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediapayments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rebutted_payment_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('resend_payment_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('send_payment_date', sa.DateTime(), nullable=True))
    op.alter_column('users', 'register_status', new_column_name="application_status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'application_status', new_column_name="register_status")
    op.drop_column('users', 'send_payment_date')
    op.drop_column('users', 'resend_payment_date')
    op.drop_column('users', 'rebutted_payment_date')
    op.drop_column('users', 'payment_status')
    op.drop_table('mediapayments')
    op.drop_table('payments')
    # ### end Alembic commands ###
