"""changing text to text(10000)

Revision ID: 0bcc7b331113
Revises: 57156e9d1ed1
Create Date: 2019-01-02 18:11:03.185136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcc7b331113'
down_revision = '57156e9d1ed1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
