"""splitting models into blueprints, try 8

Revision ID: 4e011db7da50
Revises: 640f247633c6
Create Date: 2018-12-28 15:46:26.314798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e011db7da50'
down_revision = '640f247633c6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
