"""removed phone from unique

Revision ID: 57156e9d1ed1
Revises: 5e0637917af6
Create Date: 2019-01-01 22:49:00.786914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57156e9d1ed1'
down_revision = '5e0637917af6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    # ### end Alembic commands ###
