"""user phone from string to integer change

Revision ID: af129f7679ed
Revises: 016bb05edafc
Create Date: 2018-12-28 22:56:59.771714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af129f7679ed'
down_revision = '016bb05edafc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
