"""added attributes to users

Revision ID: ed7092afc0b5
Revises: 0206cf6d0e72
Create Date: 2019-01-12 17:19:12.874739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7092afc0b5'
down_revision = '0206cf6d0e72'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('degree_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('university_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'university_name')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'degree_name')
    op.drop_column('users', 'company')
    op.drop_column('users', 'address')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
