"""role user one to one

Revision ID: 0be927e6fdc7
Revises: e8637ae073c2
Create Date: 2018-12-28 10:41:23.077126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be927e6fdc7'
down_revision = 'e8637ae073c2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('documents', 'title')
    op.add_column('messagerecipients', sa.Column('recipientgroup_id', sa.Integer(), nullable=True))
    op.drop_constraint('messagerecipients_recipient_group_id_fkey', 'messagerecipients', type_='foreignkey')
    op.create_foreign_key(None, 'messagerecipients', 'messagegroups', ['recipientgroup_id'], ['id'])
    op.drop_column('messagerecipients', 'recipient_group_id')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('messagerecipients', sa.Column('recipient_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messagerecipients', type_='foreignkey')
    op.create_foreign_key('messagerecipients_recipient_group_id_fkey', 'messagerecipients', 'messagegroups', ['recipient_group_id'], ['id'])
    op.drop_column('messagerecipients', 'recipientgroup_id')
    op.add_column('documents', sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('documents', 'name')
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
