"""user privileges >-< table

Revision ID: 56f9f8d7385d
Revises: dae3632fff00
Create Date: 2018-12-27 23:43:24.238622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f9f8d7385d'
down_revision = 'dae3632fff00'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privileges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_privilege',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('privilege_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['privilege_id'], ['privileges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_privilege')
    op.drop_table('privileges')
    # ### end Alembic commands ###
