"""fixed education document relationship

Revision ID: dae3632fff00
Revises: 67a1ccebc58d
Create Date: 2018-12-27 23:33:42.875369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae3632fff00'
down_revision = '67a1ccebc58d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('education_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'educations', ['education_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'education_id')
    # ### end Alembic commands ###
